import type { InventoryMovement, InventoryMovementForm, MovementType, Product } from '../../types'

export function EntriesHeader({ onExport, onEntry, onExit }: { onExport: () => void; onEntry: () => void; onExit: () => void }) {
  return <div className="section-header"><div><h2 className="section-title">Entradas, Salidas e Historial</h2><span style={{ fontSize: '0.8rem', color: 'var(--text-dim)' }}>Trazabilidad de cada movimiento de inventario registrado</span></div><div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}><button type="button" className="btn-outline" onClick={onExport}><i className="ti ti-download" /> Exportar CSV</button><button type="button" className="btn-secondary" onClick={onExit}><i className="ti ti-arrow-bar-to-up" /> Registrar salida</button><button type="button" className="btn-primary" onClick={onEntry}><i className="ti ti-arrow-bar-to-down" /> Registrar entrada</button></div></div>
}

export function EntriesSummary({ movementCount, incoming, outgoing }: { movementCount: number; incoming: number; outgoing: number }) {
  return <div className="stock-summary-grid"><div className="stock-summary-card primary"><div className="summary-label">Movimientos registrados</div><div className="summary-value">{movementCount}</div><div className="summary-foot">Historial completo</div></div><div className="stock-summary-card success"><div className="summary-label">Unidades de entrada</div><div className="summary-value">+{incoming}</div><div className="summary-foot">Producción y reembolsos</div></div><div className="stock-summary-card warning"><div className="summary-label">Unidades de salida</div><div className="summary-value">-{outgoing}</div><div className="summary-foot">Daños y defectos</div></div></div>
}

export function EntriesFilters({ filter, onChange }: { filter: 'todos' | MovementType; onChange: (filter: 'todos' | MovementType) => void }) {
  return <div className="filters-row"><div className="period-pills" style={{ display: 'inline-flex' }}>{([['todos', 'Todos'], ['entrada', 'Entradas'], ['salida', 'Salidas']] as const).map(([value, label]) => <button key={value} type="button" className={`pill ${filter === value ? 'active' : ''}`} onClick={() => onChange(value)}>{label}</button>)}</div></div>
}

export function EntriesTable({ visible, formatter }: { visible: InventoryMovement[]; formatter: Intl.DateTimeFormat }) {
  return <div className="table-card"><table><thead><tr><th>Fecha</th><th>Producto</th><th>Cantidad</th><th>Tipo</th><th>Motivo</th><th>Responsable</th></tr></thead><tbody>{visible.length ? visible.flatMap((movement) => movement.items.map((item) => <tr key={`${movement.id}-${item.productId}`}><td><span style={{ fontFamily: 'monospace', color: 'var(--text-dim)' }}>{formatter.format(new Date(movement.date))}</span></td><td><div className="product-cell"><div className="product-thumb">📦</div><div className="product-name">{item.productName}</div></div></td><td><strong style={{ color: movement.type === 'entrada' ? 'var(--success)' : 'var(--danger)' }}>{movement.type === 'entrada' ? '+' : '-'}{item.quantity}</strong> unid.</td><td><span className={`badge ${movement.type === 'entrada' ? 'badge-success' : 'badge-danger'}`}>{movement.type}</span></td><td>{movement.reason}</td><td>{movement.user}</td></tr>)) : <tr><td colSpan={6} style={{ textAlign: 'center', color: 'var(--text-dim)', padding: '2rem' }}>No hay movimientos para este filtro.</td></tr>}</tbody></table></div>
}

export function MovementModal({ open, saving, type, form, products, reasons, onClose, onSubmit, onChange }: { open: boolean; saving: boolean; type: MovementType; form: InventoryMovementForm; products: Product[]; reasons: Record<MovementType, Array<InventoryMovementForm['reason']>>; onClose: () => void; onSubmit: (event: React.FormEvent) => void; onChange: (form: InventoryMovementForm) => void }) {
  if (!open) return null
  return <div className="modal-backdrop" onClick={() => !saving && onClose()}><div className="modal-card" onClick={(event) => event.stopPropagation()} style={{ maxWidth: '520px' }}><div className="modal-header"><h3 className="modal-title">Registrar {type} de inventario</h3><button type="button" className="modal-close" disabled={saving} onClick={onClose}><i className="ti ti-x" /></button></div><form onSubmit={onSubmit}><div className="modal-body"><div className="form-group"><label className="form-label">Producto *</label><select className="form-input" value={form.productId} onChange={(event) => onChange({ ...form, productId: Number(event.target.value) })} required disabled={!products.length}>{products.length ? products.map((product) => <option key={product.id} value={product.id}>{product.name} ({product.sku}) - Stock: {product.stock}</option>) : <option value={0}>No hay productos disponibles</option>}</select></div><div className="form-grid-2"><div className="form-group"><label className="form-label">Tipo *</label><select className="form-input" value={type} onChange={(event) => onChange({ ...form, reason: reasons[event.target.value as MovementType][0] })}><option value="entrada">Entrada</option><option value="salida">Salida</option></select></div><div className="form-group"><label className="form-label">Motivo *</label><select className="form-input" value={form.reason} onChange={(event) => onChange({ ...form, reason: event.target.value as InventoryMovementForm['reason'] })}>{reasons[type].map((reason) => <option key={reason} value={reason}>{reason}</option>)}</select></div></div><div className="form-group"><label className="form-label">Cantidad *</label><input type="number" min="1" className="form-input" value={form.quantity} onChange={(event) => onChange({ ...form, quantity: Number(event.target.value) })} required /></div></div><div className="modal-header" style={{ borderTop: '1px solid var(--border)', borderBottom: 'none' }}><button type="button" className="btn-secondary" disabled={saving} onClick={onClose}>Cancelar</button><button type="submit" className="btn-primary" disabled={saving || !products.length}>{saving ? 'Guardando...' : 'Confirmar movimiento'}</button></div></form></div></div>
}
