import type { CustomerAuditEntry } from '../../types'
import { MetricCard } from '../common/MetricCard'
import { formatCurrency } from '../../utils/formatters'

function formatDate(value?: string) { if (!value) return 'Sin pedidos'; const date = new Date(`${value}T00:00:00`); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('es-CO', { dateStyle: 'medium' }).format(date) }
export function CustomerAuditHeader({ loading, canExport, onExport }: { loading: boolean; canExport: boolean; onExport: () => void }) { return <div className="section-header"><div><h2 className="section-title">Auditoría de Clientes</h2><span style={{ fontSize: '0.8rem', color: 'var(--text-dim)' }}>Clientes registrados, su estado y trazabilidad comercial. Esta vista es solo de consulta.</span></div><button type="button" className="btn-outline" onClick={onExport} disabled={loading || !canExport}><i className="ti ti-download" /> Exportar CSV</button></div> }
export function CustomerAuditMetrics({ registered, active, orders }: { registered: number; active: number; orders: number }) { return <div className="metrics-grid"><MetricCard metric={{ label: 'Clientes registrados', value: String(registered), subtext: 'Cuentas con rol cliente', trendType: 'delta-up', icon: 'ti-user-check' }} /><MetricCard metric={{ label: 'Clientes activos', value: String(active), subtext: 'Disponibles para pedidos', trendType: 'delta-up', icon: 'ti-users' }} /><MetricCard metric={{ label: 'Pedidos asociados', value: String(orders), subtext: 'Trazabilidad comercial', trendType: 'delta-up', icon: 'ti-shopping-bag' }} /></div> }
export function CustomerAuditFilters({ query, status, loading, onQuery, onStatus, onReload }: { query: string; status: 'todos' | 'activo' | 'inactivo'; loading: boolean; onQuery: (value: string) => void; onStatus: (value: 'todos' | 'activo' | 'inactivo') => void; onReload: () => void }) { return <div className="filters-row"><input type="search" className="form-input" style={{ maxWidth: '360px' }} placeholder="Buscar por nombre, documento, correo o teléfono..." value={query} onChange={(event) => onQuery(event.target.value)} /><select className="form-input small" style={{ width: 'auto' }} value={status} onChange={(event) => onStatus(event.target.value as typeof status)}><option value="todos">Todos los estados</option><option value="activo">Activos</option><option value="inactivo">Inactivos</option></select><button type="button" className="btn-outline" onClick={onReload} disabled={loading}><i className={`ti ${loading ? 'ti-loader-2' : 'ti-refresh'}`} /> {loading ? 'Actualizando...' : 'Actualizar'}</button></div> }
export function CustomerAuditTable({ customers, loading }: { customers: CustomerAuditEntry[]; loading: boolean }) { return <div className="table-card"><table><thead><tr><th>Cliente</th><th>Contacto</th><th>Registro</th><th>Estado</th><th>Pedidos</th><th>Total comprado</th><th>Último pedido</th></tr></thead><tbody>{!loading && customers.length === 0 ? <tr><td colSpan={7} style={{ textAlign: 'center', color: 'var(--text-dim)', padding: '32px' }}>No hay clientes que coincidan con los filtros actuales.</td></tr> : customers.map((customer) => <tr key={`${customer.id}-${customer.name}`}><td><strong>{customer.name}</strong><br /><span style={{ fontSize: '0.78rem', color: 'var(--text-dim)' }}>{customer.document}</span></td><td><span>{customer.email}</span><br /><span style={{ fontSize: '0.78rem', color: 'var(--text-dim)' }}>{customer.phone}</span></td><td><span className={`badge ${customer.registered ? 'badge-success' : 'badge-neutral'}`}>{customer.registered ? 'Registrado' : 'En pedidos'}</span></td><td><span className={`badge ${customer.status === 'activo' ? 'badge-success' : 'badge-danger'}`}>{customer.status}</span></td><td>{customer.orders}</td><td><strong>{formatCurrency(customer.totalSpent)}</strong></td><td>{formatDate(customer.lastOrderDate)}</td></tr>)}</tbody></table></div> }
